version: '3.1'

services:
  postgres:
    image: postgres
    container_name: reversed_olio
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=reversed_olio
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

volumes:
  db-data:
